config/routes.rb
BoysVsGirls::Application.routes.draw do
  devise_for :users

  root to: "dashboard#show"
  match 'message/create' => 'messages#create', via: :post

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  attr_accessible :text, :user_id
  validates :text, :user_id, :presence => true

  scope :latest,  ->(n) { reverse.limit(n) }
  scope :reverse, -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates :name, :format => { :with => /\A[a-z0-9]+\Z/i }, :allow_nil => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @messages = Message.latest(20)
    respond_to do |format|
      format.html # dashboard.html.erb
      format.json { render json: @message }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @message = Message.new(params[:message])
    @message.user_id = current_user.id
    if @message.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
        format.json {render json: @message,
status: :created, location: @message}

      end
    else
      flash[:alert] = 'Error'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {})
    gravatar_id = Digest::MD5.hexdigest((user.email || user.id).to_s.downcase)
    image_tag "http://www.gravatar.com/avatar/#{gravatar_id}?s=32&d=identicon&r=PG", { :alt =>  "user #{user.id}" }.merge(options)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.haml
%h1 Boys vs Girls
= form_for Message.new, url: message_create_path, method: :post, remote: true do |f|
  = f.label 'text', 'Text'
  = f.text_field 'text'
  = f.submit 'Save', class: 'btn btn-large btn-primary'

- @messages.each do |message|
  %p
    = gravatar_for message.user
    = message.text

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Boys vs Girls"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = javascript_include_tag :defaults
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-static-top
      .navbar-inner
        .container
          = link_to "Boys and Girls", root_path, class: 'brand'
          .container.nav-collapse
            %ul.nav.pull-right
              - unless user_signed_in?
                %li= link_to "Sign In", new_user_session_path
                %li= link_to "Sign Up", new_user_registration_path
              - else
                %li.navbar-text
                  = gravatar_for current_user
                  = current_user.email
                %li= link_to "Sign Out", destroy_user_session_path, method: :delete

    .container

      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Boys vs Girls

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"